### ISSUE TITLE
Client-side handling of events

### ISSUE THREAD

**Issue by dfalling** [gaslight/phoenix-custom-event-hook#4]
Hi, first off thanks for this hook! It's really simplified passing custom events to my backend.

Do you have any plans to support client-side handling as well? Eg the various `phx-*` hooks can be passed JS structs which will execute client-side instead of server-side. If I try this with these handlers, Phoenix just errors about not having a `handle_event` for the various JS pieces (such as `add_class`).

**Comment by superchris** [comment]
I'd be happy to look at a PR for it, but it's probably not high on my list to do myself. TBH, the JS structs kinda seemed like the wrong direction to me, I remember how remote JS turned out in Rails :) This is obviously just my opinion, and if there was a way to incorporate this feature that didn't have too much downsides I'd be happy to look at it.

**Comment by dfalling** [comment]
That's fair! I'm working around it for now, but if this bugs me enough I'll take a stab at it. Thanks!
